/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class CodeKataTest {
    @Test public void testAppCreation() {
        CodeKataTest classUnderTest = new CodeKataTest();
        assertNotNull(classUnderTest);
    }
}
