/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;

public class CodeKata {
    public static void main(String[] args) {
        System.out.println("CodeKata");
        JavaSummary summary = new JavaSummary();
        summary.summaryMain();
    }

    public static void printCurrentPath() {
        String path = new File(".").getAbsoluteFile().getParent();
        System.out.println(path);
    }
}
